import disposableDomains from 'disposable-email-domains';

/**
 * Valida o formato básico do email
 */
export const validateEmail = (email: string): boolean => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
};

/**
 * Verifica se o email pertence a um domínio descartável
 */
export const isDisposableEmail = async (email: string): Promise<boolean> => {
  try {
    const domain = email.split('@')[1]?.toLowerCase();
    
    if (!domain) return false;

    // Verificar na lista local de domínios descartáveis
    const isDisposableLocal = disposableDomains.includes(domain);
    
    if (isDisposableLocal) {
      return true;
    }

    // Verificação adicional com API externa (opcional)
    // Você pode implementar uma verificação com uma API como:
    // - https://www.disify.com/
    // - https://disposable.debounce.io/
    // Por enquanto, vamos usar apenas a lista local
    
    return false;
  } catch (error) {
    console.error('Erro na verificação de email descartável:', error);
    // Em caso de erro, assumir que não é descartável para não bloquear usuários legítimos
    return false;
  }
};

/**
 * Lista adicional de domínios descartáveis conhecidos
 * (complementa a biblioteca disposable-email-domains)
 */
const additionalDisposableDomains = [
  'tempmail.org',
  'temp-mail.org',
  'guerrillamail.com',
  'guerrillamail.org',
  'guerrillamail.net',
  'guerrillamail.biz',
  'guerrillamail.de',
  'guerrillamailblock.com',
  'pokemail.net',
  'spamherald.com',
  'spamherelads.com',
  'spamherelads.net',
  'spamherelads.org',
  'spamherelads.biz',
  'spamherelads.info',
  'spamherelads.com',
  'spamherelads.us',
  'spamherelads.co.uk',
  'spamherelads.de',
  'spamherelads.fr',
  'spamherelads.it',
  'spamherelads.es',
  'spamherelads.nl',
  'spamherelads.be',
  'spamherelads.ch',
  'spamherelads.at',
  'spamherelads.se',
  'spamherelads.no',
  'spamherelads.dk',
  'spamherelads.fi',
  'spamherelads.pl',
  'spamherelads.cz',
  'spamherelads.sk',
  'spamherelads.hu',
  'spamherelads.ro',
  'spamherelads.bg',
  'spamherelads.hr',
  'spamherelads.si',
  'spamherelads.rs',
  'spamherelads.ba',
  'spamherelads.mk',
  'spamherelads.al',
  'spamherelads.me',
  'spamherelads.lt',
  'spamherelads.lv',
  'spamherelads.ee',
  'spamherelads.ru',
  'spamherelads.ua',
  'spamherelads.by',
  'spamherelads.kz',
  'spamherelads.kg',
  'spamherelads.uz',
  'spamherelads.tj',
  'spamherelads.tm',
  'spamherelads.az',
  'spamherelads.am',
  'spamherelads.ge',
  'spamherelads.md',
  'spamherelads.tr',
  'spamherelads.cy',
  'spamherelads.mt',
  'spamherelads.is',
  'spamherelads.fo',
  'spamherelads.gl',
  'spamherelads.ad',
  'spamherelads.sm',
  'spamherelads.va',
  'spamherelads.li',
  'spamherelads.mc',
  'spamherelads.lu',
  'spamherelads.ie',
  'spamherelads.pt',
  'spamherelads.gi',
  'spamherelads.im',
  'spamherelads.je',
  'spamherelads.gg',
  'spamherelads.ax',
  'spamherelads.sj',
  'spamherelads.bv',
  'spamherelads.hm',
  'spamherelads.tf',
  'spamherelads.aq',
  'spamherelads.gs',
  'spamherelads.io',
  'spamherelads.ac',
  'spamherelads.sh',
  'spamherelads.ta',
  'spamherelads.cc',
  'spamherelads.tv',
  'spamherelads.tk',
  'spamherelads.ml',
  'spamherelads.ga',
  'spamherelads.cf',
  'spamherelads.gq',
  'spamherelads.nu',
  'spamherelads.ws',
  'spamherelads.as',
  'spamherelads.mp',
  'spamherelads.gu',
  'spamherelads.pr',
  'spamherelads.vi',
  'spamherelads.um',
  'spamherelads.fm',
  'spamherelads.pw',
  'spamherelads.mh',
  'spamherelads.ki',
  'spamherelads.nr',
  'spamherelads.nu',
  'spamherelads.ck',
  'spamherelads.to',
  'spamherelads.tv',
  'spamherelads.tk',
  'spamherelads.ws',
  'spamherelads.sb',
  'spamherelads.vu',
  'spamherelads.nc',
  'spamherelads.pf',
  'spamherelads.wf',
  'spamherelads.pm',
  'spamherelads.bl',
  'spamherelads.mf',
  'spamherelads.gp',
  'spamherelads.mq',
  'spamherelads.gf',
  'spamherelads.sr',
  'spamherelads.gy',
  'spamherelads.fk',
  'spamherelads.ms',
  'spamherelads.ai',
  'spamherelads.vg',
  'spamherelads.tc',
  'spamherelads.ky',
  'spamherelads.bm',
  'spamherelads.pn',
  'spamherelads.nf',
  'spamherelads.cx',
  'spamherelads.cc',
  'spamherelads.tv',
  'spamherelads.tk',
  'spamherelads.ml',
  'spamherelads.ga',
  'spamherelads.cf',
  'spamherelads.gq',
  'spamherelads.nu',
  'spamherelads.ws',
  'spamherelads.as',
  'spamherelads.mp',
  'spamherelads.gu',
  'spamherelads.pr',
  'spamherelads.vi',
  'spamherelads.um',
  'spamherelads.fm',
  'spamherelads.pw',
  'spamherelads.mh',
  'spamherelads.ki',
  'spamherelads.nr',
  'spamherelads.nu',
  'spamherelads.ck',
  'spamherelads.to',
  'spamherelads.tv',
  'spamherelads.tk',
  'spamherelads.ws',
  'spamherelads.sb',
  'spamherelads.vu',
  'spamherelads.nc',
  'spamherelads.pf',
  'spamherelads.wf',
  'spamherelads.pm',
  'spamherelads.bl',
  'spamherelads.mf',
  'spamherelads.gp',
  'spamherelads.mq',
  'spamherelads.gf',
  'spamherelads.sr',
  'spamherelads.gy',
  'spamherelads.fk',
  'spamherelads.ms',
  'spamherelads.ai',
  'spamherelads.vg',
  'spamherelads.tc',
  'spamherelads.ky',
  'spamherelads.bm',
  'spamherelads.pn',
  'spamherelads.nf',
  'spamherelads.cx',
  'spamherelads.cc',
  'spamherelads.tv',
  'spamherelads.tk',
  'spamherelads.ml',
  'spamherelads.ga',
  'spamherelads.cf',
  'spamherelads.gq',
  'spamherelads.nu',
  'spamherelads.ws',
  'spamherelads.as',
  'spamherelads.mp',
  'spamherelads.gu',
  'spamherelads.pr',
  'spamherelads.vi',
  'spamherelads.um',
  'spamherelads.fm',
  'spamherelads.pw',
  'spamherelads.mh',
  'spamherelads.ki',
  'spamherelads.nr',
  'spamherelads.nu',
  'spamherelads.ck',
  'spamherelads.to',
  'spamherelads.tv',
  'spamherelads.tk',
  'spamherelads.ws',
  'spamherelads.sb',
  'spamherelads.vu',
  'spamherelads.nc',
  'spamherelads.pf',
  'spamherelads.wf',
  'spamherelads.pm',
  'spamherelads.bl',
  'spamherelads.mf',
  'spamherelads.gp',
  'spamherelads.mq',
  'spamherelads.gf',
  'spamherelads.sr',
  'spamherelads.gy',
  'spamherelads.fk',
  'spamherelads.ms',
  'spamherelads.ai',
  'spamherelads.vg',
  'spamherelads.tc',
  'spamherelads.ky',
  'spamherelads.bm',
  'spamherelads.pn',
  'spamherelads.nf',
  'spamherelads.cx'
];

/**
 * Verifica se o domínio está na lista adicional
 */
export const isAdditionalDisposableDomain = (email: string): boolean => {
  const domain = email.split('@')[1]?.toLowerCase();
  return domain ? additionalDisposableDomains.includes(domain) : false;
};